sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "10.15.1"
notifications:
  slack:
    on_success: always
    rooms:
      - tensult:78YvxKn9R9EyXKMPWnKhQPVh#builds
cache:
  directories:
    - node_modules
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"
script:
  - "npm run test:coverage"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
install:
  - "npm install"
